config/routes.rb
TimeKeepingSystem::Application.routes.draw do
  get "companies/new"

  get "companies/create"

  get "company/new"

  get "company/create"

  root to: 'timers#new'

  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/signup', to: 'users#new'
   
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :edit, :update]
  resources :companies, only: [:new, :create] do
    resources :projects, only: :index
  end
  resources :projects, only: [:new, :create]
  resources :timers, only: [:index, :show, :new, :create, :edit, :update] do
    member do
      post 'stop'
      post 'start'
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :manage, :all
  end
end

app/models/company.rb
class Company < ActiveRecord::Base
  attr_protected
  
  validates :name, presence: true
  
  has_many :projects, dependent: :destroy
  has_many :tasks, through: :projects
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :company
  attr_accessible :name, :company_id

  validates :company_id, presence: true
  validates :name, presence: true
  
  has_many :tasks, class_name: 'Timer'
end

app/models/timer.rb
class Timer < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
  attr_accessible :description, :duration, :project_id
  
  validates :project, presence: true

  def start
    self.last_activated_at = Time.now
    self.save
  end
  
  def stop
    self.duration += (Time.now - self.last_activated_at)/3600
    self.last_activated_at = nil
    self.save
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation, :role
  has_secure_password
  
  
  before_save { self.email.downcase! }
  before_create :generate_remember_token
  
  has_many :timers
  
  #Validations
  validates :name, presence: true, length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, 
                    uniqueness: { case_sensitive: false }

  validates :password, presence: true, length: { minimum: 6 }, on: :create
  validates :password_confirmation, presence: true, on: :create

  
  
  ROLES = [
    [0, "User"],
    [1, "Admin"]
  ]
  
  def generate_remember_token
    begin
        self.remember_token = SecureRandom.urlsafe_base64
    end while self.class.exists?(remember_token: self.remember_token)
  end
  
  private :generate_remember_token
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  respond_to :html
  before_filter :signed_in_user
  load_and_authorize_resource

  def new
  end

  def create
    if @company.save
      flash[:success] = 'Company successfully created.'
    end
    
    respond_with @company, location: new_timer_path
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  respond_to :html, :json
  before_filter :signed_in_user
  load_and_authorize_resource :company
  load_and_authorize_resource through: :company, shallow: true

  def index
    render json: @projects.map{|p| [p.name, p.id]}
  end

  def new
  end

  def create
    if @project.save
      flash[:success] = "Project successfully created."
    end
    respond_with @project
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_filter :already_signed_in, only: [:new]

  def new
  end
  
  def create
    user = User.find_by_email(params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to root_path
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end
  
  def destroy
    sign_out
    redirect_to root_path
  end

  

  private

  def already_signed_in
    redirect_to root_path if signed_in?
  end
end

app/controllers/timers_controller.rb
class TimersController < ApplicationController
  respond_to :html
  before_filter :signed_in_user
  load_and_authorize_resource

  def index
    @timers = current_user.timers
  end

  def show
  end
  
  def new
  end
  
  def create
    @timer.user = current_user
    if @timer.save
      flash[:success] = "Timer was successfully created."
    end
    respond_with @timer
  end
  
  def edit
  end
  
  def update
    if @timer.update_attributes params[:timer]
      flash[:success] = "Timer was successfully updated."
    end
    respond_with @timer
  end
  
  def start
    @timer.start
    respond_with @timer
  end
  
  def stop
    @timer.stop
    respond_with @timer
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  respond_to :html
  load_and_authorize_resource

  def new
  end

  def create
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the TimeKeeping System!"
    end
    respond_with @user
  end

  def edit
  end

  def update
    if @user.update_attributes params[:user]
      flash[:success] = "Profile was successfuly updated."
    end
    respond_with [:edit, @user]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def current_user?(user)
    user == current_user
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.fullpath
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_path, notice: "Please sign in."
    end
  end
end

app/views/companies/_form.html.haml
.row
  .span6.offset3
    = render 'shared/error_messages', object:@company
    
    = form_for(@company) do |f|
      
      = f.label :name
      = f.text_field :name
    
      = f.label :email
      = f.text_field :email
      
      = f.label :website
      = f.text_field :website
      
      = f.label :first_address, 'Address 1'
      = f.text_field :first_address
      
      = f.label :second_address, 'Address 2'
      = f.text_field :second_address
      
      = f.label :third_address, 'Address 3'
      = f.text_field :third_address
      
      = f.label :city
      = f.text_field :city
      
      = f.label :state
      = f.text_field :state
      
      = f.label :zip
      = f.text_field :zip
      
      = f.label :first_phone, 'Phone 1'
      = f.text_field :first_phone
      
      = f.label :second_phone, 'Phone 2'
      = f.text_field :second_phone
      
      = f.label :first_fax, 'Fax 1'
      = f.text_field :first_fax
      
      = f.label :second_fax, 'Fax 2'
      = f.text_field :second_fax
      
      = f.submit class: "btn btn-large btn-primary"

app/views/companies/new.html.haml
%h1 Create a Company
= render 'form'

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top
  .navbar-inner
    .container
      = link_to "TimeKeeping", root_path, id: "logo"
      %nav
        %ul.nav.pull-right
          -if signed_in?
            -if can?(:create, Company)
              %li= link_to "Add Company", new_company_path
            -if can?(:create, Project)
              %li= link_to "Add Project", new_project_path
            %li= link_to "Create a Timer", new_timer_path
            %li= link_to "Sign out", signout_path, method: "delete"
          -else
            %li= link_to "Sign in", signin_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TimeKeepingSystem</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    = render 'layouts/header'
    .container
      - flash.each do |key, value|
        %div{class: "alert alert-#{key}"}= value
      = yield

app/views/projects/_form.html.haml
.row
  .span6.offset3
    = form_for(@project) do |f|
      = render 'shared/error_messages', object:@project
            
      = f.label :name
      = f.text_field :name
      
      = f.label :company_id
      = f.select :company_id, Company.all.map {|c| [c.name, c.id]}
      
      = f.submit class: "btn btn-large btn-primary"

app/views/projects/new.html.haml
%h1 Create Project
= render 'form' 

app/views/shared/_error_messages.html.haml
- if object.errors.any?
  #error_explanation
    .alert.alert-error The form contains #{pluralize(object.errors.count, "error")}
    %ul
      - object.errors.full_messages.each do |msg|
        %li="* #{msg}"

app/views/timers/_form.html.haml
.row
  .span6.offset3
    = form_for(@timer) do |f|
      = render 'shared/error_messages', object:@timer
            
      = label_tag :customer
      = select_tag :company, options_for_select(Company.all.map{|c| [c.name, c.id]})
      
      = f.label :project_id, "Project"
      = f.select :project_id, []

      = f.label :duration
      = f.text_field :duration
      
      = f.label :description
      = f.text_area :description
      
      = f.submit class: "btn btn-large btn-primary"

app/views/timers/_timer.html.haml
%tr
  %td= link_to timer.id, timer
  %td= timer.duration
  %td= timer.project.company.name
  %td= timer.project.name

app/views/timers/edit.html.haml
%h1 Edit your Timer
= render 'form'

app/views/timers/index.html.haml
%table
  %tr
    %th Timer
    %th Duration
    %th Company
    %th Project
  = render @timers

app/views/timers/new.html.haml
%h1 Create a Timer
= render 'form'

app/views/timers/show.html.haml
%p= link_to "Edit Timer", [:edit, @timer]
%table
  %tr
    %td Duration
    %td= number_with_precision @timer.duration, precision: 2
  %tr
    %td Company
    %td= @timer.project.company.name
  %tr
    %td Project
    %td= @timer.project.name
  %tr
    %td Timer
    - if @timer.last_activated_at.nil?
      %td= link_to "Start Timer", start_timer_path(@timer), method: :post
    - else
      %td= link_to "Stop Timer", stop_timer_path(@timer), method: :post

app/views/users/_form.html.haml
.row
  .span6.offset3
    = form_for(@user) do |user|
      = render 'shared/error_messages', object:@user
            
      = user.label :name
      = user.text_field :name
      
      = user.label :email
      = user.text_field :email
      
      = user.label :password
      = user.password_field :password
      
      = user.label :password_confirmation, "Confirm Password"
      = user.password_field :password_confirmation
      
      =user.submit class: "btn btn-large btn-primary"

app/views/users/edit.html.haml
%h1 Update your profile
= render "form"

app/views/users/new.html.haml
%h1 Sign up
= render 'form'